defaults: &defaults
  working_directory: ~/repo  
  docker:
    - image: circleci/openjdk:8-jdk

version: 2
jobs:
    build:
      <<: *defaults

      environment:
        # Customize the JVM maximum heap limit
        MAVEN_OPTS: -Xmx3200m

      steps:        
        - checkout
        
        - restore_cache:
            keys:
              - eclipse-platform-{{ checksum "org.eclipse.epsilon.labs.updatesite.interim/site.xml" }}
              - eclipse-platform-

        # Download Eclipse platform, this will be cached
        - run:
            command: |
              curl -O http://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/oxygen/R/eclipse-java-oxygen-R-linux-gtk-x86_64.tar.gz
              tar -zxvf eclipse-java-oxygen-R-linux-gtk*.tar.gz
        
        # Each entry in projects.txt is used to fetch the persisted artifacts and publish them as features
        # and bundles
        - run:
            <projects.txt xargs -n1 | while read f; read g; do ./publishFeatures.sh $f $g $DOWNLOAD_ARTIFACTS; done

        # Crate interim updatesite site.xml dynamically
        - run: 
            command: |
              find ./epsilonlabs-artifacts -type f -name "site.xml" | xargs -I % cat % > site.xml
              grep -vE "<site>|</site>|<?xml" site.xml > tmp.xml
              echo "</site>" >> tmp.xml
              rm site.xml
              echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" >> site.xml
              echo "<site>" >> site.xml
              cat tmp.xml >> site.xml
              rm tmp.xml
              mv site.xml ~/repo/org.eclipse.epsilon.labs.updatesite/site.xml
              
        # Persit site.xml
        - store_artifacts:
          path: ~/repo/org.eclipse.epsilon.labs.updatesite/site.xml
          destination: site.xml

        - run: mvn clean package

        - save_cache:
            key: eclipse-platform-{{ checksum "org.eclipse.epsilon.labs.updatesite.interim/site.xml" }}
            paths:
              - eclipse

        # Deploy to bintray 
        - run: 
            command |
            version = mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version
            ./pushToBintray.sh $BINTRAY_USER $BINTRAY_API_KEY epsilonlabs updates updatesite 1.$CIRCLE_BUILD_NUM org.eclipse.epsilon.labs.updatesite/target/site





